import './globals.css'
import { Raleway } from 'next/font/google'

import Navbar from '@/components/common/navbar'
import Footer from '@/components/common/footer'

const inter = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-nbaige h-screen w-screen flex flex-col items-center justify-start '>{children}</div>
      </body>
    </html>
  )
}
