import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '@/components/common/navbar'
import Footer from '@/components/common/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen w-screen flex flex-col items-center justify-center '>{children}</div>
        {/* <div className='h-screen w-screen flex flex-col items-center justify-center bg-gradient-to-r from-primary to-[#144271]'>{children}</div> */}
      </body>
    </html>
  )
}
